{{- $name := .Chart.Name -}}
{{- $env := required "You forgot to set env, don't you ?" .Values.global.env -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $name }}-{{ $env }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: "helm"
    meta.helm.sh/release-name: "gitlab2sentry"
    meta.helm.sh/release-namespace: "team-infrastructure"
data:
  GITLAB_TOKEN: {{ .Values.secret.gitlab_token | b64enc }}
  SENTRY_TOKEN: {{ .Values.secret.sentry_token | b64enc }}