apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ $.Chart.Name }}-{{ .Values.global.env }}"
  namespace: {{ .Values.global.namespace }}
data:
  {{- with .Values.secrets.data }}
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{ end }}
