global:
  env: production
  app: gitlab2sentry
  namespace: team-infrastructure

secret:
  gitlab_token: !vault secrets/team-infrastructure/production/gitlab2sentry#gitlab_api_key
  sentry_token: !vault secrets/team-infrastructure/production/gitlab2sentry#sentry_token

cronjob:
  image: "registry.numberly.in/team-infrastructure/gitlab2sentry"
  imagePullPolicy: "IfNotPresent"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  activeDeadlineSeconds: 800
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 10
  securityContext:
    runAsUser: 65534 # nobody
  jobs:
    - name: 'gitlab2sentry'
      schedule: '*/15 * * * *'
      env:
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              key: GITLAB_TOKEN
              name: gitlab2sentry-production
        - name: SENTRY_TOKEN
          valueFrom:
            secretKeyRef:
              key: SENTRY_TOKEN
              name: gitlab2sentry-production
        - name: SENTRY_DSN
          value: https://7dbff29bc3e049829ba89831c20fa21e@sentry.numberly.net/64
        - name: SENTRY_URL
          value: https://sentry.numberly.net
        - name: GITLAB_URL
          value: https://gitlab.numberly.in
