global:
  env: production
  app: gitlab2sentry
  namespace: team-infrastructure

secret:
  gitlab_token: your-vault-gitlab-token-path
  sentry_token: your-vault-sentry-token-path

cronjob:
  image: "your-image-registry-path"
  imagePullPolicy: "IfNotPresent"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  activeDeadlineSeconds: 800
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 10
  securityContext:
    runAsUser: your-user-id
  jobs:
    - name: 'gitlab2sentry'
      schedule: your-crontab-schedule
      env:
        # Sentry values
        - name: SENTRY_TOKEN
          valueFrom:
            secretKeyRef:
              key: SENTRY_TOKEN
              name: gitlab2sentry-production
        - name: SENTRY_DSN
          value: your-sentry-dsn
        - name: SENTRY_URL
          value: your-sentry-url
        - name: SENTRY_ORG_SLUG
          value: your-sentry-organization-slug
        # Gitlab values
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              key: GITLAB_TOKEN
              name: gitlab2sentry-production
        - name: GITLAB_URL
          value: your-gitlab-url
          # DSN MR (1) values
        - name: GITLAB_DSN_MR_CONTENT
          value: |
            ## File generated by gitlab2sentry
            [defaults]
            url = {sentry_url}
            dsn = {dsn}
            project = {project_slug}
        - name: GITLAB_DSN_MR_DESCRIPTION
          value: |
            {mentions} Congrats, your Sentry project has been
            created, merge this
            to finalize your Sentry integration of
            {name_with_namespace} :clap: :cookie:
        - name: GITLAB_DSN_MR_BRANCH_NAME
          value: auto_add_sentry_dsn
        - name: GITLAB_DSN_MR_TITLE
          value: "[gitlab2sentry] Merge me to add your sentry DSN to {project_name}"
          # Sentryclirc MR (2) values
        - name: GITLAB_SENTRYCLIRC_MR_CONTENT
          value: |
            ## File generated by gitlab2sentry
            [defaults]
            url = {sentry_url}
        - name: GITLAB_SENTRYCLIRC_MR_DESCRIPTION
          value: |
            {mentions} Merge this and it will automatically
            create a Sentry project \n
            for {name_with_namespace} :cookie:
        - name: GITLAB_SENTRYCLIRC_MR_BRANCH_NAME
          value: auto_add_sentry
        - name: GITLAB_SENTRYCLIRC_MR_FILEPATH
          value: .sentryclirc
        - name: GITLAB_SENTRYCLIRC_MR_COMMIT_MSG
          value: Update .sentryclirc
        - name: GITLAB_SENTRYCLIRC_MR_TITLE
          value: "[gitlab2sentry] Merge me to add sentry to {project_name} or close me"
          # Gitlab configuration values
        - name: GITLAB_GRAPHQL_SUFFIX
          value: api/graphql
        # - name: GITLAB_MENTIONS
        #   value:
        #     - "@all"
        - name: GITLAB_MENTIONS_ACCESS_LEVEL
          value: 40
        - name: GITLAB_CREATION_DAYS_LIMIT
          value: 60
        - name: GITLAB_MR_KEYWORD
          value: sentry
        - name: GITLAB_REMOVE_SOURCE
          value: true
        - name: GITLAB_GROUP_IDENTIFIER
          value: your-group-identifier
        - name: GITLAB_AIOHTTP_TIMEOUT
          value: 60
        - name: GITLAB_GRAPHQL_PAGE_LENGTH
          value: 100
